# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Xumple' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', '~> 5.2'
pod 'SnapKit', '~> 5.0.0'
pod 'SwiftLint'
pod 'SwiftJWT'
pod 'IQKeyboardManagerSwift'

  # Pods for Xumple
post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
  end
 end
end

end
